plugins {
    id 'application'
    id 'idea'
}

group = 'org.alteredmechanism'
version = '1.0.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass = 'org.alteredmechanism.hwaetd.Hwaetd'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'net.java.dev.jna:jna:5.17.0'
    implementation 'net.java.dev.jna:jna-platform:5.17.0'
}

idea {
    module {
        downloadJavadoc = true
        downloadSources = true
    }
}
